# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('username', models.TextField()),
                ('source', models.TextField()),
                ('screen_name', models.CharField(max_length=255)),
                ('profile_image', models.TextField()),
                ('hash_tag', models.CharField(max_length=255)),
            ],
        ),
    ]
