# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('source', models.TextField()),
                ('screen_name', models.CharField(max_length=255)),
                ('profile_image', models.TextField()),
            ],
        ),
    ]
